{"uuid":"5db1240d-b43f-4a4d-be7f-3d44b60f3ee2","historyId":"c5cfc5a88e51e37573deac8a2133c31","fullName":"Orangehrm.testcases.LoginPageTestCases.loginTestCaseInavalid","labels":[{"name":"package","value":"Orangehrm.testcases.LoginPageTestCases"},{"name":"testClass","value":"Orangehrm.testcases.LoginPageTestCases"},{"name":"testMethod","value":"loginTestCaseInavalid"},{"name":"parentSuite","value":"Default Suite"},{"name":"suite","value":"OrangeHrm"},{"name":"subSuite","value":"Orangehrm.testcases.LoginPageTestCases"},{"name":"host","value":"kamalesh"},{"name":"thread","value":"1084@kamalesh.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"},{"name":"epic","value":"EP001"},{"name":"story","value":"SP00-Login test Cases"},{"name":"severity","value":"critical"}],"links":[],"name":"loginTestCaseInavalid","status":"failed","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"","trace":"java.lang.AssertionError: \r\n\tat org.testng.AssertJUnit.fail(AssertJUnit.java:65)\r\n\tat org.testng.AssertJUnit.assertTrue(AssertJUnit.java:23)\r\n\tat org.testng.AssertJUnit.assertTrue(AssertJUnit.java:33)\r\n\tat Orangehrm.testcases.LoginPageTestCases.loginTestCaseInavalid(LoginPageTestCases.java:59)\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\r\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:566)\r\n\tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)\r\n\tat org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)\r\n\tat org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)\r\n\tat org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)\r\n\tat org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)\r\n\tat org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)\r\n\tat org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)\r\n\tat org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)\r\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1541)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:764)\r\n\tat org.testng.TestRunner.run(TestRunner.java:585)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:384)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:286)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1140)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1069)\r\n\tat org.testng.TestNG.run(TestNG.java:1037)\r\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)\r\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)\r\n"},"stage":"finished","description":"Check the user able to login with invalid Credentials.","steps":[{"name":"Verfing the Login with invalid credentials","status":"failed","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"","trace":"java.lang.AssertionError: \r\n\tat org.testng.AssertJUnit.fail(AssertJUnit.java:65)\r\n\tat org.testng.AssertJUnit.assertTrue(AssertJUnit.java:23)\r\n\tat org.testng.AssertJUnit.assertTrue(AssertJUnit.java:33)\r\n\tat Orangehrm.testcases.LoginPageTestCases.loginTestCaseInavalid(LoginPageTestCases.java:59)\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\r\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:566)\r\n\tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)\r\n\tat org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)\r\n\tat org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)\r\n\tat org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)\r\n\tat org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)\r\n\tat org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)\r\n\tat org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)\r\n\tat org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)\r\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1541)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:764)\r\n\tat org.testng.TestRunner.run(TestRunner.java:585)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:384)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:286)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1140)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1069)\r\n\tat org.testng.TestNG.run(TestNG.java:1037)\r\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)\r\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)\r\n"},"stage":"finished","steps":[{"name":"Login","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[{"name":"user","value":" "},{"name":"pwd","value":" "}],"start":1708440364158,"stop":1708440364982},{"name":"Check error message is present","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[{"name":"errMessage","value":"Username cannot be empty"}],"start":1708440364982,"stop":1708440365024}],"attachments":[],"parameters":[{"name":"Username","value":" "},{"name":"password","value":" "},{"name":"errMessage","value":"Username cannot be empty"}],"start":1708440364158,"stop":1708440365024}],"attachments":[{"name":"saveFailureScreenShot","source":"563c3940-56f8-4f7b-9ede-429c339cd923-attachment"},{"name":"loginTestCaseInavalid failed and screenshot taken!","source":"d99b8658-0a59-4cfd-8a4a-51ad6f8db68c-attachment","type":"text/plain"}],"parameters":[{"name":"arg2","value":"Username cannot be empty"},{"name":"arg1","value":" "},{"name":"arg0","value":" "}],"start":1708440364157,"stop":1708440365142}